### ISSUE TITLE
Where silead_ts firmware to be placed?

### ISSUE THREAD

**Issue by Split7fire** [onitake/gslx680-acpi#17]
Trying to make touchscreen work on Chuwi Hibook. Some history:
- I've started with SileadTouch.sys
- I've used cat & dd to extract firmware
- I've used fwtool to convert firmware

But now the main question: where to place silead_ts?
Thanks in advance.

**Comment by onitake** [comment]
It should go directly into `/lib/firmware`, so the kernel can pick it up.
