### ISSUE TITLE
Building from Make file on 4.15.0-33 kernel - error: code model kernel does not support PIC mode

### ISSUE THREAD

**Issue by SMB784** [onitake/gslx680-acpi#29]
Just to start, I am running Lubuntu 18.04 with kernel version 4.15.0-33 on an Insignia NS-P11W7100.

I have been trying to build gslx680-acpi using the make command, and the build process returns this error:

sean@Lethe:~/gslx680-acpi$ make
make -C /lib/modules/4.15.0-33-generic/build ARCH=x86_64 CROSS_COMPILE= M=/home/sean/gslx680-acpi modules
make[1]: Entering directory '/usr/src/linux-headers-4.15.0-33-generic'
  CC [M]  /home/sean/gslx680-acpi/gslx680_ts_acpi.o
**cc1: error: code model kernel does not support PIC mode**
scripts/Makefile.build:339: recipe for target '/home/sean/gslx680-acpi/gslx680_ts_acpi.o' failed
make[2]: *** [/home/sean/gslx680-acpi/gslx680_ts_acpi.o] Error 1
Makefile:1552: recipe for target '_module_/home/sean/gslx680-acpi' failed
make[1]: *** [_module_/home/sean/gslx680-acpi] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-4.15.0-33-generic'
Makefile:18: recipe for target 'modules' failed
make: *** [modules] Error 2

After googling this error, it seemed to be an issue with the GCC version, so I applied the patch found at this link: https://askubuntu.com/questions/851433/kernel-doesnt-support-pic-mode-for-compiling

However when I do that, more errors crop up:

make
make -C /lib/modules/4.15.0-33-generic/build ARCH=x86_64 CROSS_COMPILE= M=/home/sean/gslx680-acpi modules
make[1]: Entering directory '/usr/src/linux-headers-4.15.0-33-generic'
  CC [M]  /home/sean/gslx680-acpi/gslx680_ts_acpi.o
In file included from /home/sean/gslx680-acpi/gslx680_ts_acpi.c:18:0:
./include/linux/types.h:17:9: error: unknown type name ‘__kernel_ino_t’
 typedef __kernel_ino_t  ino_t;
         ^~~~~~~~~~~~~~
./include/linux/types.h:18:9: error: unknown type name ‘__kernel_mode_t’
 typedef __kernel_mode_t  mode_t;
         ^~~~~~~~~~~~~~~
./include/linux/types.h:21:9: error: unknown type name ‘__kernel_off_t’
 typedef __kernel_off_t  off_t;
         ^~~~~~~~~~~~~~
./include/linux/types.h:22:9: error: unknown type name ‘__kernel_pid_t’
 typedef __kernel_pid_t  pid_t;
         ^~~~~~~~~~~~~~
./include/linux/types.h:23:9: error: unknown type name ‘__kernel_daddr_t’
 typedef __kernel_daddr_t daddr_t;
         ^~~~~~~~~~~~~~~~
./include/linux/types.h:25:9: error: unknown type name ‘__kernel_suseconds_t’
 typedef __kernel_suseconds_t suseconds_t;
         ^~~~~~~~~~~~~~~~~~~~
./include/linux/types.h:26:9: error: unknown type name ‘__kernel_timer_t’
 typedef __kernel_timer_t timer_t;
         ^~~~~~~~~~~~~~~~
./include/linux/types.h:27:9: error: unknown type name ‘__kernel_clockid_t’
 typedef __kernel_clockid_t clockid_t;
         ^~~~~~~~~~~~~~~~~~
./include/linux/types.h:32:9: error: unknown type name ‘__kernel_uid32_t’
 typedef __kernel_uid32_t uid_t;
         ^~~~~~~~~~~~~~~~
./include/linux/types.h:33:9: error: unknown type name ‘__kernel_gid32_t’
 typedef __kernel_gid32_t gid_t;
         ^~~~~~~~~~~~~~~~
./include/linux/types.h:34:9: error: unknown type name ‘__kernel_uid16_t’
 typedef __kernel_uid16_t        uid16_t;
         ^~~~~~~~~~~~~~~~
./include/linux/types.h:35:9: error: unknown type name ‘__kernel_gid16_t’
 typedef __kernel_gid16_t        gid16_t;
         ^~~~~~~~~~~~~~~~
./include/linux/types.h:41:9: error: unknown type name ‘__kernel_old_uid_t’
 typedef __kernel_old_uid_t old_uid_t;
         ^~~~~~~~~~~~~~~~~~
./include/linux/types.h:42:9: error: unknown type name ‘__kernel_old_gid_t’
 typedef __kernel_old_gid_t old_gid_t;
         ^~~~~~~~~~~~~~~~~~
./include/linux/types.h:46:9: error: unknown type name ‘__kernel_loff_t’
 typedef __kernel_loff_t  loff_t;
         ^~~~~~~~~~~~~~~
./include/linux/types.h:55:9: error: unknown type name ‘__kernel_size_t’
 typedef __kernel_size_t  size_t;
         ^~~~~~~~~~~~~~~
./include/linux/types.h:60:9: error: unknown type name ‘__kernel_ssize_t’
 typedef __kernel_ssize_t ssize_t;
         ^~~~~~~~~~~~~~~~
./include/linux/types.h:65:9: error: unknown type name ‘__kernel_ptrdiff_t’
 typedef __kernel_ptrdiff_t ptrdiff_t;
         ^~~~~~~~~~~~~~~~~~
./include/linux/types.h:70:9: error: unknown type name ‘__kernel_time_t’
 typedef __kernel_time_t  time_t;
         ^~~~~~~~~~~~~~~
./include/linux/types.h:75:9: error: unknown type name ‘__kernel_clock_t’
 typedef __kernel_clock_t clock_t;
         ^~~~~~~~~~~~~~~~
./include/linux/types.h:80:9: error: unknown type name ‘__kernel_caddr_t’
 typedef __kernel_caddr_t caddr_t;
         ^~~~~~~~~~~~~~~~
./include/linux/types.h:199:2: error: unknown type name ‘__kernel_daddr_t’
  __kernel_daddr_t f_tfree;
  ^~~~~~~~~~~~~~~~
./include/linux/types.h:200:2: error: unknown type name ‘__kernel_ino_t’
  __kernel_ino_t  f_tinode;
  ^~~~~~~~~~~~~~
In file included from ./include/linux/list.h:9:0,
                 from ./include/linux/module.h:9,
                 from /home/sean/gslx680-acpi/gslx680_ts_acpi.c:19:
./include/linux/kernel.h:6:10: fatal error: stdarg.h: No such file or directory
 #include <stdarg.h>
          ^~~~~~~~~~
compilation terminated.
scripts/Makefile.build:339: recipe for target '/home/sean/gslx680-acpi/gslx680_ts_acpi.o' failed
make[2]: *** [/home/sean/gslx680-acpi/gslx680_ts_acpi.o] Error 1
Makefile:1558: recipe for target '_module_/home/sean/gslx680-acpi' failed
make[1]: *** [_module_/home/sean/gslx680-acpi] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-4.15.0-33-generic'
Makefile:18: recipe for target 'modules' failed
make: *** [modules] Error 2

I am building from the source downloaded via git from this repository.  Is there something that I am doing wrong, or missing?  It seems like a GCC issue but I dont know how to fix it.

**Comment by onitake** [comment]
I can't reproduce this on Debian testing with kernel 4.17.0-3.

It looks like you're trying to compile the module with a different compiler than the one used to build the kernel - please note that Debain and derivatives (Ubuntu, ....) have a separate gcc package for kernel and module building.

Don't try to patch gcc yourself, just install `linux-kbuild-4.15` - the kernel makefiles should pick it up automatically.
