### ISSUE TITLE
Make the module compile with Ubuntu 18.04

### ISSUE THREAD

**Issue by Yes21** [onitake/gslx680-acpi#30]
I can have the module compiling with Ubuntu 18.04.
I'm running from error to error :

1- **`cc1: error: code model kernel does not support PIC mode`**
Solution was to modify the linux source kernel Makefile (`/usr/src/linux-headers-4.15.0-43-generic`) adding `-fno-pie` after `KBUILD_CFLAGS` :
```
KBUILD_CFLAGS   := -Wall -Wundef -Wstrict-prototypes -Wno-trigraphs \
		   -fno-strict-aliasing -fno-common -fshort-wchar \
		   -Werror-implicit-function-declaration \
		   -Wno-format-security \
		   -std=gnu89  -fno-pie
```

2-**` fatal error: 'stdarg.h' file not found`**
Solution :
```
$ cd /lib/modules/$(uname -r)/build/include
$ sudo ln -s $(gcc -print-file-name=include)/stdarg.h
```

3- **`fatal error: 'asm/linkage.h' file not found`**
Didn't find any solution right now ...

If somebody already succeed in compiling on Ubuntu 18.04, any help is welcome.

Thanks

**Comment by Yes21** [comment]
Sorry I didn't see this closed issue (https://github.com/onitake/gslx680-acpi/issues/29).
But I can't find a "linux-kbuild-4.15" package !

**Comment by Yes21** [comment]
**`cc1: error: code model kernel does not support PIC mode`**

A better way to solve this issue would be to ad this to the Makefile :

```
# Support kernel PIC mode for compiling
EXTRA_CFLAGS += $(USER_EXTRA_CFLAGS) -fno-pie
```
Will test it tomorrow ...

**Comment by onitake** [comment]
As I mentioned in onitake/gsl-firmware#91 , linux-kbuild is Debian specific. Ubuntu uses a different method for building kernels.

I don't know the the specifics, but https://wiki.ubuntu.com/Kernel/BuildYourOwnKernel should help.

It's important that the same compiler and compiler flags are used for modules and the kernel.
Perhaps it helps to run
```bash
sudo apt-get build-dep linux-image-4.15.0-43-generic
```
?
