### ISSUE TITLE
Fusion5 FWIN232

### ISSUE THREAD

**Issue by syco** [onitake/gslx680-acpi#35]
Hi all..
I've got myself into a pickle.. I formatted my tablet to try Android and now can't get the touch to work in any system, including windows since I don't have the original drivers.
How do I figure out if one of the already extracted firmwares works on my device?
Thanks

**Comment by onitake** [comment]
You should probably open such issues on https://github.com/onitake/gsl-firmware instead.

To answer your question: It's very likely none of them will work properly. Each firmware contains calibration data that is specific to a particular device.

You can certainly try different firmware, but there's no guarantee what will happen to your device, although I doubt a mismatched firmware will be able cause any damage.

Your best bet is still the manufacturer, and you're pretty much out of your luck if they haven't published any drivers for this device. Maybe ask around if someone else with the same tablet can send you the driver files?
