### ISSUE TITLE
Setting axis in the firmware?

### ISSUE THREAD

**Issue by sigboe** [onitake/gslx680-acpi#7]
So I think I figured out the resolution of my touch screen to be 1700x1125. Or at least if I start with a fresh boot with display settings clockwise, load a firmware with -w 1700 and -h 1125 it tracks 1:1 but one of the axis is reversed. Is there a way to specify this in the firmware?

**Comment by onitake** [comment]
Yes, in fact there is. Use fwtool to set the xflip or yflip flag. The feature is still untested, though.

**Comment by sigboe** [comment]
That's great, gonna try this today. Might I suggest you rename them to `-wflip` and `-hflip` to be consistent with `-w` and `-h`

**Comment by onitake** [comment]
Ok. Sounds good, but I'm just going to change that in fwtool, not the driver.

If the calibration is wrong, it's not that big a deal to redo it, I think. :)
Optimally, one shouldn't have to do any calibration at all.

**Comment by onitake** [comment]
On second thought, hflip is ambiguous. It could be interpreted as 'horizontal' flip.

I'll keep the parameters as they are, perhaps with some clarifications in the help text and readme. I could turn the various -f arguments into standalone parameters, but one-letter options are better IMHO.
